### ISSUE TITLE
monotone functionality

### ISSUE THREAD

**Issue by danielmork** [danielmork/dlmtree#13]
Setting dlm.type to 'monotone' does not result in a monotone ERC. I think this setting results in calling TDLNM, not Monotone TDLNM.

**Comment by danielmork** [comment]
On additional investigation, there may also be issues with the monotone tdlnm function. Changing model$class="monotone" did not resolve the issue. Please use branch 'hotfix_tdlnm_se_monotone' to explore problem and find solution

**Comment by SeongwonIm** [comment]
I am updating the monotone tdlnm cpp function for ctr->Y0 and ctr->Ystar as they replaced ctr->Y.

**Comment by SeongwonIm** [comment]
monotone tdlnm runs but still running into 'Error: std::bad_alloc' and 'segfault error'

**Comment by danielmork** [comment]
It may be similar to the TDLNM issue we were having—that there is an input missing or incorrect passed from the dlmtree() function. Perhaps check back on these?

From: Seongwon Im ***@***.***>
Date: Wednesday, May 15, 2024 at 11:34
To: danielmork/dlmtree ***@***.***>
Cc: Daniel Mork ***@***.***>, Author ***@***.***>
Subject: Re: [danielmork/dlmtree] monotone functionality (Issue #13)

monotone tdlnm runs but still running into 'Error: std::bad_alloc' and 'segfault error'

**Comment by SeongwonIm** [comment]
Updated monotone-TDLNM model. The ZINB flag was dropped while merging, causing the segfault error. Also updated model$shape to only be available for a single exposure case to avoid a warning from 'mean(tdlnm.exposure.se)' when tdlnm.exposure.se = NULL.

**Comment by danielmork** [comment]
There is no place in dlmtree() that sets model$class = 'monotone', which is needed to call monotdlnm_cpp().

**Comment by SeongwonIm** [comment]
Lines 551 and 567 set model$class = 'monotone' when model$monotone is TRUE.

**Comment by danielmork** [comment]
Got it! I was looking in the wrong branch. Thanks

**Comment by SeongwonIm** [comment]
Specifying dlm.type = "monotone" and shrinkage in dlmtree.R results in incorrect estimates. The original code set shrinkage to FALSE by default when monotone model is specified.

**Comment by SeongwonIm** [comment]
Also note that the scaling and centering of the fixed effect matrix (model$Z) of the original code of tdlnm.R are different to dlmtree.R so the estimates will be slightly different.
