### ISSUE TITLE
Unnecessary files on 'master'?

### ISSUE THREAD

**Issue by danielmork** [danielmork/dlmtree#15]
Since the dlmtree website is located on the gh-pages branch, it seems like a range of files and folders are not needed in the master branch. These include:

- .github/
- .vscode/
- docs/
- pkgdown/

Is there a good way to remove these but still keep them active locally or in another branch? Other suggestions?

**Comment by AnderWilson** [comment]
This is resolved.  The .github folder remains but the other folders have been removed.
