### ISSUE TITLE
It is  -Wno-ignored-attributes

### ISSUE THREAD

**Issue by rsparapa** [danielmork/dlmtree#3]
For me the magic clause to avoid all the garbage is  -Wno-ignored-attributes
rather than  -Wno-ignored-attribute which is what you have in the Makevars.
I also like to have more than that...
-Wno-deprecated-declarations -Wno-parentheses -Wno-ignored-attributes -Wno-unused-function

**Comment by danielmork** [comment]
Thanks for pointing out this mistake. Makevars have been updated to include the correct flag and additional flags you noted.
