### ISSUE TITLE
if(verbose) cat(...)

### ISSUE THREAD

**Issue by SeongwonIm** [danielmork/dlmtree#40]
Not really spotting what the CRAN review is talking about for dlmtree.R and estDLM.R. We have if(verbose) cat(...) for all console output. The only thing I can think of for estDLM.R is the additional tick marks condition.

For printing a data frame of exposure levels using adj_coexposure.R (Line 57-59), we have to either remove it or use cat to print them separately.

**Comment by danielmork** [comment]
Let's add a 'verbose=TRUE' function input into adj_coexposure.R and then preface each cat(...) or print(...) with an if (verbose). I think the main goal is to be able to control all console output generated by the package unless there are explicit calls to print.class(...) functions.

**Comment by SeongwonIm** [comment]
Okay, so I have already updated them like that so we should be good then. Pull request coming up.
